mypro/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup')   
]

mypro/mypro/urls.py
from django.contrib import admin
from django.conf.urls import  include
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('login/', views.LoginPage.as_view(), name='loginview'),
    path('logout/', views.LogoutPage.as_view(), name='logoutview'),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('accounts/',include('django.contrib.auth.urls')),
    path('groups/',include('groups.urls',namespace='groups')),
    path("posts/",include("posts.urls", namespace="post")),
    
]

mypro/posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'new/$', views.CreatePost.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)/$',views.UserPosts.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(), name='single'),
    url(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete')
]

mypro/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Social</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
        integrity="undefined" crossorigin="anonymous">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
        integrity="undefined" crossorigin="anonymous">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="undefined"crossorigin="anonymous"></script>
    <link rel="stylesheet" href=" {% static 'mypro/css/mypro3.css'  %} ">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body>
    <div class="bg"></div>
    <div class="bg bg2"></div>
    <div class="bg bg3"></div>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e79a5b;">
        <div class="container">
            <a class="navbar-brand" href="#">
                <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <a href="{% url 'posts:create' %}" class="nav-link active"><i class="bi bi-blockquote-left"></i>Post</a>
                <a href="{% url 'groups:all' %}" class="nav-link active"><i class="bi bi-people-fill"></i>Groups</a></>
                <a href="#" class="nav-link active"><i class="bi bi-person-lines-fill"></i>Create Group</a>
                <a href="{% url 'accounts:logout' %}" class="nav-link active">Log out</a>
                {% else %}
                <a href=" {% url 'groups:all' %} " class="nav-link active" ><i class="bi bi-people-fill"></i>Groups</a>
                <a href="{% url 'accounts:login' %}" class="nav-link active"><i class="bi bi-person-bounding-box"></i>Log In</a>
                <a href="{% url 'accounts:signup' %}" class="nav-link active"><i class="bi bi-person-plus-fill"></i></i>Sign Up</a>
                {% endif %}
                </ul>                
            </a>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

mypro/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Hello</h1>
</div>

{% endblock content %}

mypro/templates/loginview.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>You are logged in</h1>
</div>

{% endblock content %}

mypro/templates/logoutview.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Thank you for visiting!</h1>
</div>

{% endblock content %}